name = "QuantumEspressoDatasets"
uuid = "aaad41db-e042-4bbd-ad47-e353d5c615c8"
authors = ["Junfeng Qiao", "Guoyuan Liu", "Aleksandr Poliukhin"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
